export const ICONS = [
  "bx bx-dollar",
  "bx bx-euro",
  "bx bx-bitcoin",
  "bx bx-credit-card",

  "bx bx-wallet",
  "bx bx-wallet-alt",
  "bx bx-lock-alt",

  "bx bx-transfer",
  "bx bx-transfer-alt",
  "bx bx-receipt",
  "bx bx-barcode",

  "bx bx-trending-up",
  "bx bx-trending-down",
  "bx bx-line-chart",
  "bx bx-bar-chart",
  "bx bx-bar-chart-alt",
  "bx bx-pie-chart",
  "bx bx-pie-chart-alt",

  "bx bx-calculator",
  "bx bx-notepad",
  "bx bx-spreadsheet",
  "bx bx-file",
  "bx bx-file-blank",

  "bx bx-cart",
  "bx bx-cart-alt",
  "bx bx-shopping-bag",
  "bx bx-home",
  "bx bx-gas-pump",
  "bx bx-car",
  "bx bx-bus",

  "bx bx-dish",
  "bx bx-donate-heart",
  "bx bx-movie-play",
  "bx bx-party",
];

export const COLORS = [
  "#FFB3BA",
  "#FFDFBA",
  "#FFFFBA",
  "#BAFFC9",
  "#BAE1FF",
  "#E0BBE4",
  "#D5F4E6",
  "#FEE1E8",
  "#F6DFEB",
  "#F0EAD6",
  "#D6EAF8",
  "#D1F2EB",
  "#FADBD8",
  "#FDEBD0",
  "#FCF3CF",
  "#EBDEF0",
  "#D2B4DE",
  "#A9CCE3",
  "#A3E4D7",
  "#F9E79F",
  "#F5CBA7",
  "#F7DC6F",
  "#AED6F1",
  "#FAD7A0",
  "#E8DAEF",
  "#D7BDE2",
  "#F9E79F",
  "#F6DDCC",
  "#D1F0B1",
  "#C5FAD5",
  "#FFC9DE",
  "#FFE0AC",
  "#C1E1C1",
  "#FFEDC1",
  "#E2F0CB",
  "#F6CED8",
  "#C4F0F0",
];

export const MONTHS_ABREV = [
  "JAN",
  "FEV",
  "MAR",
  "ABR",
  "MAI",
  "JUN",
  "JUL",
  "AGO",
  "SET",
  "OUT",
  "NOV",
  "DEZ",
].filter((month, index) => index < new Date().getMonth() + 1);
